version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres  # lowercase consistent with typical usage
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"     # Match the port your backend listens on (usually 8000)
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"      # Typical frontend port
    environment:
      - VITE_BACKEND_URL= https://kasongo-chat-production-703e.up.railway.app # Use internal Docker network for local dev
    depends_on:
      - backend

volumes:
  pgdata:
